Add PR template
Otus-DevOps-2018-02/hostberg_microservices pull request #1
Opened 2018-03-05 13:51 UTC by hostberg

Добавил шаблон для Pull Request'ов.

2018-03-12 17:42 UTC, vitkhab requested changes
Заполни, пожалуйста, описание PR согласно шаблону.

2018-03-12 18:59 UTC, hostberg commented
Спасибо, исправлено. Описание PR приведено в соответствие шаблону.

2018-03-13 08:57 UTC, vitkhab approved these changes
Все выглядит классно. Молодец! Можно мерджить.

2018-03-13 10:03 UTC, merged

2018-03-13 10:04 UTC, hostberg commented
Спасибо.